// Code generated by MockGen. DO NOT EDIT.
// Source: src/usecase/accountrole/accountrole.go

// Package mock_accountrole is a generated GoMock package.
package mock_accountrole

import (
	context "context"
	reflect "reflect"

	model "github.com/achwanyusuf/bricksvc/src/domain/model"
	gomock "github.com/golang/mock/gomock"
)

// MockAccountRoleInterface is a mock of AccountRoleInterface interface.
type MockAccountRoleInterface struct {
	ctrl     *gomock.Controller
	recorder *MockAccountRoleInterfaceMockRecorder
}

// MockAccountRoleInterfaceMockRecorder is the mock recorder for MockAccountRoleInterface.
type MockAccountRoleInterfaceMockRecorder struct {
	mock *MockAccountRoleInterface
}

// NewMockAccountRoleInterface creates a new mock instance.
func NewMockAccountRoleInterface(ctrl *gomock.Controller) *MockAccountRoleInterface {
	mock := &MockAccountRoleInterface{ctrl: ctrl}
	mock.recorder = &MockAccountRoleInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccountRoleInterface) EXPECT() *MockAccountRoleInterfaceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockAccountRoleInterface) Create(ctx context.Context, v model.CreateAccountRole) (model.AccountRole, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, v)
	ret0, _ := ret[0].(model.AccountRole)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockAccountRoleInterfaceMockRecorder) Create(ctx, v interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAccountRoleInterface)(nil).Create), ctx, v)
}

// DeleteByID mocks base method.
func (m *MockAccountRoleInterface) DeleteByID(ctx context.Context, id int64, isHardDelete bool, vid int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByID", ctx, id, isHardDelete, vid)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByID indicates an expected call of DeleteByID.
func (mr *MockAccountRoleInterfaceMockRecorder) DeleteByID(ctx, id, isHardDelete, vid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByID", reflect.TypeOf((*MockAccountRoleInterface)(nil).DeleteByID), ctx, id, isHardDelete, vid)
}

// GetByID mocks base method.
func (m *MockAccountRoleInterface) GetByID(ctx context.Context, cacheControl string, id int64) (model.AccountRole, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, cacheControl, id)
	ret0, _ := ret[0].(model.AccountRole)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockAccountRoleInterfaceMockRecorder) GetByID(ctx, cacheControl, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockAccountRoleInterface)(nil).GetByID), ctx, cacheControl, id)
}

// GetByParam mocks base method.
func (m *MockAccountRoleInterface) GetByParam(ctx context.Context, cacheControl string, v model.GetAccountRolesByParam) ([]model.AccountRole, model.Pagination, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByParam", ctx, cacheControl, v)
	ret0, _ := ret[0].([]model.AccountRole)
	ret1, _ := ret[1].(model.Pagination)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetByParam indicates an expected call of GetByParam.
func (mr *MockAccountRoleInterfaceMockRecorder) GetByParam(ctx, cacheControl, v interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByParam", reflect.TypeOf((*MockAccountRoleInterface)(nil).GetByParam), ctx, cacheControl, v)
}
