// Code generated by SQLBoiler 4.16.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package entity

var TableNames = struct {
	AccountRoles     string
	Accounts         string
	Roles            string
	SchemaMigrations string
	TransferJobs     string
}{
	AccountRoles:     "account_roles",
	Accounts:         "accounts",
	Roles:            "roles",
	SchemaMigrations: "schema_migrations",
	TransferJobs:     "transfer_jobs",
}
